spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  config:
    import:
      - secret.yml

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true