spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ec2-13-125-224-220.ap-northeast-2.compute.amazonaws.com:3306/egomogo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: egomogo
    password: 6daysegomogo2023

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true